Repository OpenCTI-Platform/client-python, pull requests merged in 2024-07, with the labels that each got.

#694 [client-python] Fix isort
  pycti/__init__.py
Labels: filigran team

#703 [client-python] Fix linter for channel
  pycti/__init__.py
Labels: filigran team, do not merge

#697 [client] Support of KEV field for vulnerability entity (#7390)
  pycti/entities/opencti_vulnerability.py
Labels: filigran team, multi-repository

#708 [client-python] get all report's properties when using csv mapper (#6947)
  pycti/entities/opencti_report.py
Labels: filigran team, multi-repository
