Repository OpenCTI-Platform/client-python, pull requests merged in 2024-05, with the labels that each got.

#621 Bug fix for issue OpenCTI-Platform#586
  pycti/entities/opencti_intrusion_set.py
Labels: community

#633 [client] Fix export an entity even if the status worfklow does not exist
  pycti/utils/opencti_stix2.py
Labels: filigran team

#634 [client-python] Add max_marking support to all exports
  pycti/entities/opencti_stix_object_or_stix_relationship.py
  pycti/utils/opencti_stix2.py
Labels: filigran team

#632 [client-python] upload_file now accepts optional arg file_markings (#631)
  examples/upload_file.py
  pycti/api/opencti_api_client.py
Labels: filigran team

#639 [client] Improve client to support looping control (#6930)
  pycti/api/opencti_api_client.py
  pycti/api/opencti_api_playbook.py
  pycti/connector/opencti_connector_helper.py
Labels: filigran team

#651 Enable multi repository CI for forks (#7062)
  .drone.yml
  scripts/clone-opencti.sh
Labels: multi-repository

#670 [client] Report Full export (STIX/JSON) doesn't include relationships (#669)
  pycti/entities/opencti_stix_core_relationship.py
  pycti/entities/opencti_stix_nested_ref_relationship.py
  pycti/entities/opencti_stix_object_or_stix_relationship.py
  pycti/entities/opencti_stix_sighting_relationship.py
Labels: filigran team
