Repository OpenCTI-Platform/client-python, pull requests merged in 2024-04, with the labels that each got.

#514 Observable enhancements
  pycti/__init__.py
  pycti/entities/opencti_stix_core_object.py
  pycti/entities/opencti_stix_cyber_observable.py
  pycti/utils/constants.py
  pycti/utils/opencti_stix2_utils.py
Labels: community

#604 [client] Add support to write connectors bundle to files and/or to queue (#603)
  pycti/api/opencti_api_client.py
  pycti/api/opencti_api_work.py
  pycti/connector/opencti_connector_helper.py
Labels: feature

#614 [client] typo in pycti/entities/opencti_stix_cyber_observable.py (#6681)
  pycti/entities/opencti_stix_cyber_observable.py
Labels: filigran team

#616 [drone] Update for PR of community
  .drone.yml
Labels: filigran team

#624 [client] Define file marking definitions (#opencti/issue/5797)
  pycti/entities/opencti_stix_core_object.py
  pycti/entities/opencti_stix_cyber_observable.py
  pycti/entities/opencti_stix_domain_object.py
Labels: filigran team

#610 [client] Removed linked-to ref reference
  pycti/utils/constants.py
Labels: filigran team
