Repository OpenCTI-Platform/client-python, pull requests merged in 2024-08, with the labels that each got.

#707 [client] Add EPSS Support for Vulnerability Entity (#3568)
  pycti/entities/opencti_stix_core_object.py
  pycti/entities/opencti_stix_domain_object.py
  pycti/entities/opencti_stix_object_or_stix_relationship.py
  pycti/entities/opencti_vulnerability.py
Labels: filigran team, multi-repository

#640 [client] added persona support
  pycti/__init__.py
  pycti/entities/opencti_stix_core_object.py
  pycti/entities/opencti_stix_cyber_observable.py
  pycti/entities/stix_cyber_observable/opencti_stix_cyber_observable_properties.py
  pycti/utils/constants.py
Labels: multi-repository

#718 [client] Release 6.2.15
  pycti/__init__.py
Labels: filigran team
