Repository OpenCTI-Platform/client-python, pull requests merged in 2025-03, with the labels that each got.

#859 [deps]: loose requests required versions
  requirements.txt
  setup.cfg
Labels: bug, filigran team

#853 [client] Add get_all arg in list api for TA (#758)
  pycti/entities/opencti_threat_actor.py
  pycti/entities/opencti_threat_actor_group.py
  pycti/entities/opencti_threat_actor_individual.py
Labels: filigran team

#851 [client] Introduce api protocol helper for listening connectors (#850)
  pycti/api/opencti_api_client.py
  pycti/api/opencti_api_connector.py
  pycti/connector/opencti_connector.py
  pycti/connector/opencti_connector_helper.py
  requirements.txt
Labels: filigran team, multi-repository

#863 [client] add `force_validation` to `send_stix2_bundle` (#9760)
  pycti/connector/opencti_connector_helper.py
Labels: filigran team
