Repository OpenCTI-Platform/client-python, pull requests merged in 2025-02, with the labels that each got.

#828 [client] Add administrative entities and functionality
  docs/pycti/pycti.api.opencti_api_client.rst
  docs/pycti/pycti.api.opencti_api_connector.rst
  docs/pycti/pycti.api.opencti_api_job.rst
  docs/pycti/pycti.api.rst
  docs/pycti/pycti.connector.opencti_connector.rst
  docs/pycti/pycti.connector.opencti_connector_helper.rst
  docs/pycti/pycti.connector.rst
  docs/pycti/pycti.entities.opencti_attack_pattern.rst
  docs/pycti/pycti.entities.opencti_campaign.rst
  docs/pycti/pycti.entities.opencti_capability.rst
  docs/pycti/pycti.entities.opencti_course_of_action.rst
  docs/pycti/pycti.entities.opencti_external_reference.rst
  docs/pycti/pycti.entities.opencti_group.rst
  docs/pycti/pycti.entities.opencti_identity.rst
  docs/pycti/pycti.entities.opencti_incident.rst
  docs/pycti/pycti.entities.opencti_indicator.rst
  docs/pycti/pycti.entities.opencti_intrusion_set.rst
  docs/pycti/pycti.entities.opencti_kill_chain_phase.rst
  docs/pycti/pycti.entities.opencti_malware.rst
  docs/pycti/pycti.entities.opencti_marking_definition.rst
  docs/pycti/pycti.entities.opencti_note.rst
  docs/pycti/pycti.entities.opencti_opinion.rst
  docs/pycti/pycti.entities.opencti_report.rst
  docs/pycti/pycti.entities.opencti_role.rst
  docs/pycti/pycti.entities.opencti_settings.rst
  docs/pycti/pycti.entities.opencti_stix_domain_entity.rst
  docs/pycti/pycti.entities.opencti_stix_entity.rst
  docs/pycti/pycti.entities.opencti_stix_observable.rst
  docs/pycti/pycti.entities.opencti_stix_observable_relation.rst
  docs/pycti/pycti.entities.opencti_stix_relation.rst
  docs/pycti/pycti.entities.opencti_stix_sighting.rst
  docs/pycti/pycti.entities.opencti_tag.rst
  docs/pycti/pycti.entities.opencti_threat_actor.rst
  docs/pycti/pycti.entities.opencti_tool.rst
  docs/pycti/pycti.entities.opencti_user.rst
  docs/pycti/pycti.entities.opencti_vulnerability.rst
  docs/pycti/pycti.entities.rst
  docs/pycti/pycti.rst
  docs/pycti/pycti.utils.constants.rst
  docs/pycti/pycti.utils.opencti_stix2.rst
  docs/pycti/pycti.utils.rst
  pycti/__init__.py
  pycti/api/opencti_api_client.py
  pycti/entities/opencti_capability.py
  pycti/entities/opencti_group.py
  pycti/entities/opencti_role.py
  pycti/entities/opencti_settings.py
  pycti/entities/opencti_user.py
  tests/02-integration/entities/test_entity_crud.py
  tests/02-integration/entities/test_group.py
  tests/02-integration/entities/test_role.py
  tests/02-integration/entities/test_settings.py
  tests/02-integration/entities/test_user.py
  tests/cases/entities.py
Labels: community

#829 [connector] Replace deprecated datetime.utcnow() in logger's formatter
  pycti/utils/opencti_logger.py
Labels: filigran team

#841 [deps]: Loose pydantic versions
  requirements.txt
  setup.cfg
Labels: filigran team

#810 [client] remove hardcoded first value in list method when using getAll
  pycti/entities/opencti_attack_pattern.py
  pycti/entities/opencti_campaign.py
  pycti/entities/opencti_case_incident.py
  pycti/entities/opencti_case_rfi.py
  pycti/entities/opencti_case_rft.py
  pycti/entities/opencti_channel.py
  pycti/entities/opencti_course_of_action.py
  pycti/entities/opencti_data_component.py
  pycti/entities/opencti_data_source.py
  pycti/entities/opencti_event.py
  pycti/entities/opencti_external_reference.py
  pycti/entities/opencti_feedback.py
  pycti/entities/opencti_grouping.py
  pycti/entities/opencti_identity.py
  pycti/entities/opencti_incident.py
  pycti/entities/opencti_infrastructure.py
  pycti/entities/opencti_intrusion_set.py
  pycti/entities/opencti_kill_chain_phase.py
  pycti/entities/opencti_label.py
  pycti/entities/opencti_language.py
  pycti/entities/opencti_location.py
  pycti/entities/opencti_malware.py
  pycti/entities/opencti_malware_analysis.py
  pycti/entities/opencti_marking_definition.py
  pycti/entities/opencti_narrative.py
  pycti/entities/opencti_note.py
  pycti/entities/opencti_observed_data.py
  pycti/entities/opencti_opinion.py
  pycti/entities/opencti_report.py
  pycti/entities/opencti_stix_core_object.py
  pycti/entities/opencti_stix_core_relationship.py
  pycti/entities/opencti_stix_cyber_observable.py
  pycti/entities/opencti_stix_domain_object.py
  pycti/entities/opencti_stix_nested_ref_relationship.py
  pycti/entities/opencti_stix_sighting_relationship.py
  pycti/entities/opencti_task.py
  pycti/entities/opencti_threat_actor.py
  pycti/entities/opencti_threat_actor_group.py
  pycti/entities/opencti_threat_actor_individual.py
  pycti/entities/opencti_tool.py
  pycti/entities/opencti_vulnerability.py
Labels: community

#846 [deps]: loose opentelemetry-xxx required versions (#818)
  requirements.txt
  setup.cfg
Labels: bug, filigran team
