Repository OpenCTI-Platform/client-python, pull requests merged in 2025-04, with the labels that each got.

#866 [client] Fix a spelling mistake (#8245)
  pycti/entities/opencti_indicator.py
Labels: filigran team, multi-repository

#867 [client] do not register API listening URI when using AMQP protocol
  pycti/connector/opencti_connector_helper.py
Labels: filigran team

#865 [client] add hashes to indicator observable values graphql fragment (opencti #10277)
  pycti/entities/indicator/opencti_indicator_properties.py
Labels: multi-repository

#869 [client] fix work expectations computation (Opencti #10523)
  pycti/connector/opencti_connector_helper.py
Labels: filigran team

#871 [CI] add auto label filigran team
  .github/workflows/auto-set-labels.yml
Labels: filigran team

#826 [client] added missing status in query fragments (opencti #8389)
  pycti/entities/opencti_attack_pattern.py
  pycti/entities/opencti_campaign.py
  pycti/entities/opencti_case_incident.py
  pycti/entities/opencti_case_rfi.py
  pycti/entities/opencti_case_rft.py
  pycti/entities/opencti_course_of_action.py
  pycti/entities/opencti_data_component.py
  pycti/entities/opencti_data_source.py
  pycti/entities/opencti_event.py
  pycti/entities/opencti_feedback.py
  pycti/entities/opencti_grouping.py
  pycti/entities/opencti_identity.py
  pycti/entities/opencti_incident.py
  pycti/entities/opencti_infrastructure.py
  pycti/entities/opencti_intrusion_set.py
  pycti/entities/opencti_language.py
  pycti/entities/opencti_location.py
  pycti/entities/opencti_malware.py
  pycti/entities/opencti_malware_analysis.py
  pycti/entities/opencti_narrative.py
  pycti/entities/opencti_note.py
  pycti/entities/opencti_observed_data.py
  pycti/entities/opencti_opinion.py
  pycti/entities/opencti_stix_core_relationship.py
  pycti/entities/opencti_stix_sighting_relationship.py
  pycti/entities/opencti_task.py
  pycti/entities/opencti_threat_actor_group.py
  pycti/entities/opencti_threat_actor_individual.py
  pycti/entities/opencti_tool.py
  pycti/entities/opencti_vulnerability.py
Labels: filigran team

#845 [client] Add capability to add custom headers in opencti http client (#844)
  pycti/api/opencti_api_client.py
  pycti/connector/opencti_connector_helper.py
Labels: filigran team

#884 [client] Add score on Organization
  pycti/entities/opencti_identity.py
Labels: filigran team, multi-repository

#888 [client] now use internal id when possible for patch operations
  pycti/utils/opencti_stix2.py
Labels: filigran team, multi-repository

#889 [client] test fix build target release/current
  scripts/clone-opencti.sh
Labels: filigran team
