Repository OpenCTI-Platform/client-python, pull requests merged in 2025-01, with the labels that each got.

#802 [client] [Playbook] Modify severity field with playbooks (#7648)
  pycti/entities/opencti_case_rfi.py
  pycti/entities/opencti_case_rft.py
Labels: filigran team, multi-repository

#796 Remove harcoded first value when getting all indicators
  pycti/entities/opencti_indicator.py
Labels: partner

#815 Update copyright to 2025
  docs/conf.py
Labels: filigran team

#813 [client] Hide Authorization header (opencti/9693)
  pycti/api/opencti_api_client.py
Labels: filigran team
